    await app(scope, receive, sender)

  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    response = await f(request)

               ^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 291, in app

    solved_result = await solve_dependencies(

                    ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 634, in solve_dependencies

    solved = await solve_generator(

             ^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 560, in solve_generator

    return await stack.enter_async_context(cm)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/.nix-profile/lib/python3.12/contextlib.py", line 659, in enter_async_context

    result = await _enter(cm)

             ^^^^^^^^^^^^^^^^

  File "/root/.nix-profile/lib/python3.12/contextlib.py", line 210, in __aenter__

    return await anext(self.gen)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/fastapi/concurrency.py", line 35, in contextmanager_in_threadpool

    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

  File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    await app(scope, receive, sender)

  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 735, in app

    await route.handle(scope, receive, send)

  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle

    await self.app(scope, receive, send)

  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 76, in app

    await wrap_app_handling_exceptions(app, request)(scope, receive, send)

  File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

    raise exc

  File "/opt/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app

    await app(scope, receive, sender)

  File "/opt/venv/lib/python3.12/site-packages/starlette/routing.py", line 73, in app

    response = await f(request)

               ^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/fastapi/routing.py", line 291, in app

    solved_result = await solve_dependencies(

                    ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 634, in solve_dependencies

    solved = await solve_generator(

             ^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 560, in solve_generator

    return await stack.enter_async_context(cm)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/root/.nix-profile/lib/python3.12/contextlib.py", line 659, in enter_async_context

    result = await _enter(cm)

             ^^^^^^^^^^^^^^^^

  File "/root/.nix-profile/lib/python3.12/contextlib.py", line 210, in __aenter__

    return await anext(self.gen)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/opt/venv/lib/python3.12/site-packages/fastapi/concurrency.py", line 35, in contextmanager_in_threadpool

    raise e

  File "/opt/venv/lib/python3.12/site-packages/fastapi/concurrency.py", line 27, in contextmanager_in_threadpool

    yield await run_in_threadpool(cm.__enter__)
